# Question 1

Check the number is even or odd


In [32]:
x=float(input())
if x%2==0:
    print(x,"is even")
else:
    print(x,"is odd")

22
22.0 is even


# Question 2
Given an integer, , perform the following conditional actions:

If is odd, print Weird If is even and in the inclusive range of 2 to5 , print Not Weird If is even and in the inclusive range of 6 to20 , print Weird If is even and greater than 20 , print Not Weird

In [33]:
x=int(input())
if x%2!=0:
    print("wierd")
elif (x%2==0) & (5>=x>=2):
    print("not wierd")
elif (x%2==0) & (20>=x>=6):
    print(" wierd")
elif (x%2==0) & (x>20):
    print("not wierd")

9
wierd


# Question3 
Write a Python program to get the difference between a given number and 17, if the number is greater than 17 return double the absolute difference.

In [35]:
x=int(input())
if x<17:
    print(17-x)
else:
    print((17-x)**2)

20
9


In [36]:
x=int(input())
diff=17-x
if x<17:
    print(diff)
else:
    print((diff)**2)

20
9


# Question 4
Write a Python program to sum of three given integers. However, if two values are equal sum will be zero.

In [38]:
x=int(input())
y=int(input())
z=int(input())
sum=0
if x==y or x==z or y==z:
    print(sum)
    
else:
    print(x+y+z)

4
5
6
15


# Question5
print square number in the range of your user

In [40]:
n = int(input())

for i in range(n):
    print (i * i)

5
0
1
4
9
16


# Question 6
 Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [41]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


# Question 7
2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [42]:
import numpy as np
n=np.arange(2,11).reshape(3,3)
print(n)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# Question 8
3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [43]:
import numpy as np
n1=np.zeros(10)
print(n1)
n1[6]=11
print(n1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


# Question 9
4. Write a NumPy program to convert a list and tuple into arrays.

list=[9,8,8,9]

tuple=([7,8,9],[7,7,9])


In [44]:
l1=[9,9,9,8,8]
n3=np.array(l1)
print(n3)
t1=([1,4,7],[9,9,8])
n4=np.array(t1)
print(n4)

[9 9 9 8 8]
[[1 4 7]
 [9 9 8]]


# Question 10
6-Write a NumPy program to create a new array of 3*5, filled with 2

In [45]:
n4=np.ones((3,4))*2
print(n4)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


# Question 11
8- You are given N X M integer array matrix with space separated elements ( N= rows and M= columns).
Your task is to print the transpose
the user input the values

In [46]:
import numpy as np
N,M=map(int,input().split(' '))
arr=np.array([input().split(' ') for _ in range(N)],int)
print(arr)
print(np.transpose(arr))

3 4
2 3 4 5
5 6 7 8
9 7 6 5
[[2 3 4 5]
 [5 6 7 8]
 [9 7 6 5]]
[[2 5 9]
 [3 6 7]
 [4 7 6]
 [5 8 5]]


# Question 12 project

Content

price	price in US dollars (\$326--\$18,823)

carat	weight of the diamond (0.2--5.01)

cut	quality of the cut (Fair, Good, Very Good, Premium, Ideal)

color	diamond colour, from J (worst) to D (best)

clarity	a measurement of how clear the diamond is (I1 (worst), SI2, SI1, VS2, VS1, VVS2, VVS1, IF (best))

x	length in mm (0--10.74)

y	width in mm (0--58.9)

z	depth in mm (0--31.8)

depth	total depth percentage = z / mean(x, y) = 2 * z / (x + y) (43--79)

table	width of top of diamond relative to widest point (43--95)

# 1- Question
1-read you csv file

2-print the first 5 rows

3-print the shape of the data

4- print and data type of each column

In [23]:
import pandas as pd
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print(diamonds.shape)
print(diamonds.dtypes)
diamonds.head(5)

(53940, 10)
carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object


carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

# 2-Question
1- print carat column

2- Write a Pandas program to create a new 'Quality -color' Column (cut,color)

examble => ( Ideal, E)

In [24]:
print(diamonds['carat'])

0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
         ... 
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64


In [25]:
diamonds['Quality-color']=diamonds.cut + ',' + diamonds.color
diamonds.head()

carat      cut color clarity  depth  table  price     x     y     z  \
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75   

  Quality-color  
0       Ideal,E  
1     Premium,E  
2        Good,E  
3     Premium,I  
4        Good,J

# 3-Question
1-Write a Pandas program to summarize the data.

2- only one column => 'table'



In [26]:
diamonds.describe()

carat         depth         table         price             x  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean       0.797940     61.749405     57.457184   3932.799722      5.731157   
std        0.474011      1.432621      2.234491   3989.439738      1.121761   
min        0.200000     43.000000     43.000000    326.000000      0.000000   
25%        0.400000     61.000000     56.000000    950.000000      4.710000   
50%        0.700000     61.800000     57.000000   2401.000000      5.700000   
75%        1.040000     62.500000     59.000000   5324.250000      6.540000   
max        5.010000     79.000000     95.000000  18823.000000     10.740000   

                  y             z  
count  53940.000000  53940.000000  
mean       5.734526      3.538734  
std        1.142135      0.705699  
min        0.000000      0.000000  
25%        4.720000      2.910000  
50%        5.710000      3.530000  
75%        6.540000      4.040000  
max       58.900000     31.800000

In [28]:
diamonds['table'].describe()

count    53940.000000
mean        57.457184
std          2.234491
min         43.000000
25%         56.000000
50%         57.000000
75%         59.000000
max         95.000000
Name: table, dtype: float64

# 4-Question
1-print the name of all the columns

2- Mean of each column

3-Mean of each row of diamonds DataFrame:

In [29]:
diamonds.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z', 'Quality-color'],
      dtype='object')

In [30]:
diamonds.mean()

carat       0.797940
depth      61.749405
table      57.457184
price    3932.799722
x           5.731157
y           5.734526
z           3.538734
dtype: float64

In [31]:
diamonds.mean(axis=1)

0         64.727143
1         65.292857
2         65.651429
3         66.535714
4         66.864286
            ...    
53935    412.932857
53936    412.981429
53937    413.628571
53938    413.267143
53939    412.898571
Length: 53940, dtype: float64